= libvirt

https://travis-ci.com/saltstack-formulas/libvirt-formula[image:https://travis-ci.com/saltstack-formulas/libvirt-formula.svg?branch=master[Travis CI Build Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]

Formula to setup and configure `libvirt`.

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas, please pay
attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section] for more details.

More information
https://docs.saltstack.com/en/latest/topics/tutorials/cloud_controller.html[SALT
AS A CLOUD CONTROLLER].

== Contributing to this repo

*Commit message formatting is significant!!*

Please see
xref:main::CONTRIBUTING.adoc[How
to contribute] for more details.

== Available states

=== `libvirt`

_Meta-state (This is a state that includes other states)_.

Install libvirt, qemu and extra packages; configure and start the
libvirtd service, and creates the certificates for migration.

=== `libvirt.clean`

_Meta-state (This is a state that includes other states)_.

Clean the extra and qemu packages, the server and the python package.

=== `libvirt.server`

_Meta-state (This is a state that includes other states)_.

Install libvirt packages; configure and start the libvirtd service, and
creates the certificates for migration.

=== `libvirt.server.clean`

_Meta-state (This is a state that includes other states)_.

Clean the service, the configuration files and the packages. Any
generated certificates is not handled.

=== `libvirt.server.package`

This state install the libvirt package only.

=== `libvirt.server.package.clean`

This state remove the libvirt package only and depends on
`libvirt.server.config.clean`.

=== `libvirt.server.config`

Configures libvirtd.conf and /etc/sysconfig, /etc/default, /etc/conf.d
daemon files.

=== `libvirt.server.config.clean`

Delete libvirtd.conf and /etc/sysconfig, /etc/default, /etc/conf.d
daemon files and depends on `libvirt.server.service.clean`.

=== `libvirt.server.service`

Starts the libvirtd service

=== `libvirt.server.service.clean`

Disable and stop the libvirtd service.

=== `libvirt.server.tls`

Installs the libvirt certificates to allow virtual machine migration.

=== `libvirt.qemu`

This state install the qemu package only.

=== `libvirt.qemu.clean`

This state remove the qemu package only.

=== `libvirt.extra`

This state install the extra packages only.

=== `libvirt.extra.clean`

This state remove the extra packages only.

=== `libvirt.python`

Installs the python bindings for libvirt

=== `libvirt.python.clean`

This state remove the python bindings package for libvirt only.

== Testing

Linux testing is done with `kitchen-salt`.

=== Requirements

* Ruby
* Docker

[source,bash]
----
$ gem install bundler
$ bundle install
$ bin/kitchen test [platform]
----

Where `[platform]` is the platform name defined in `kitchen.yml`, e.g.
`debian-9-2019-2-py3`.

=== `bin/kitchen converge`

Creates the docker instance and runs the `libvirt` main state, ready for
testing.

=== `bin/kitchen verify`

Runs the `inspec` tests on the actual instance.

=== `bin/kitchen destroy`

Removes the docker instance.

=== `bin/kitchen test`

Runs all of the stages above in one go: i.e. `destroy` + `converge` +
`verify` + `destroy`.

=== `bin/kitchen login`

Gives you SSH access to the instance for manual testing.
